# CMS Medicare Part D — Data Exploration

**Prerequisite:** Run `00_build_database.ipynb` first to create `cms.db`.

This notebook explores the structure and contents of the Part D geography dataset
before committing to a specific research question. Goals:
- Understand the geographic breakdown (National vs State rows)
- Survey what drug categories and therapeutic areas are present
- Identify oncology drugs available for analysis
- Check data quality (suppression rates, missing values)

In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

db_path = r"C:\Users\palla\OneDrive\Documents\Coding Projects\CMS\database\cms.db"
conn = sqlite3.connect(db_path)

## Step 1: Dataset Overview

How many rows are at the National level vs State level?
How many unique drugs are in the dataset?

In [2]:
# Row counts by geographic level
geo_summary = pd.read_sql_query("""
    SELECT Prscrbr_Geo_Lvl, COUNT(*) AS rows, COUNT(DISTINCT Gnrc_Name) AS unique_drugs
    FROM part_d_geo
    GROUP BY Prscrbr_Geo_Lvl
""", conn)

print("Geographic level summary:")
print(geo_summary)

Geographic level summary:
  Prscrbr_Geo_Lvl    rows  unique_drugs
0        National    3607          1945
1           State  112329          1868

## Step 2: Top Drugs by Total Claims (National)

What are the most-claimed drugs nationally? This gives a sense of the therapeutic
areas represented and where the data is richest.

In [3]:
top_drugs = pd.read_sql_query("""
    SELECT Gnrc_Name, Brnd_Name, Tot_Clms, Tot_Benes, Tot_Drug_Cst
    FROM part_d_geo
    WHERE Prscrbr_Geo_Lvl = 'National'
    ORDER BY Tot_Clms DESC
    LIMIT 30
""", conn)

print("Top 30 drugs by total claims (National):")
top_drugs

Top 30 drugs by total claims (National):

,Gnrc_Name,Brnd_Name,Tot_Clms,Tot_Benes,Tot_Drug_Cst
0,Atorvastatin Calcium,Atorvastatin Calcium,68467282,16770381.0,1.000314e+09
1,Amlodipine Besylate,Amlodipine Besylate,47516290,11570255.0,4.070836e+08
2,Levothyroxine Sodium,Levothyroxine Sodium,41665462,8683487.0,6.533209e+08
3,Lisinopril,Lisinopril,36064986,8746660.0,3.317373e+08
4,Gabapentin,Gabapentin,35115029,7549556.0,6.556496e+08
5,Losartan Potassium,Losartan Potassium,33183284,8187304.0,4.874522e+08
6,Metoprolol Succinate,Metoprolol Succinate,29617871,7153109.0,5.874448e+08
7,Omeprazole,Omeprazole,28132175,7294693.0,4.221951e+08
8,Rosuvastatin Calcium,Rosuvastatin Calcium,25844520,6942272.0,6.041944e+08
9,Metformin Hcl,Metformin Hcl,23861633,5915242.0,2.474325e+08
10,Pantoprazole Sodium,Pantoprazole Sodium,23641040,6188143.0,3.838448e+08
11,Furosemide,Furosemide,23014799,5637336.0,1.447957e+08
12,Apixaban,Eliquis,21185751,3925487.0,1.826613e+10
13,Hydrocodone/Acetaminophen,Hydrocodone-Acetaminophen,20015264,5186251.0,4.229598e+08
14,Tamsulosin Hcl,Tamsulosin Hcl,19856872,5072417.0,3.960331e+08
15,Hydrochlorothiazide,Hydrochlorothiazide,18347405,4900177.0,9.862509e+07
16,Trazodone Hcl,Trazodone Hcl,17032783,3663946.0,2.162974e+08
17,Albuterol Sulfate,Albuterol Sulfate Hfa,16607172,6123602.0,5.836313e+08
18,Metoprolol Tartrate,Metoprolol Tartrate,16234485,3913974.0,1.400052e+08
19,Simvastatin,Simvastatin,15944664,3915436.0,1.728751e+08
20,Sertraline Hcl,Sertraline Hcl,15245522,3039534.0,1.734869e+08
21,Carvedilol,Carvedilol,15174159,3510072.0,1.786223e+08
22,Prednisone,Prednisone,14980777,7160043.0,8.432375e+07
23,Potassium Chloride,Potassium Chloride,14139363,3477566.0,3.959986e+08
24,Clopidogrel Bisulfate,Clopidogrel,13017402,3258019.0,2.016135e+08
25,Famotidine,Famotidine,12742514,3591272.0,2.027178e+08
26,Tramadol Hcl,Tramadol Hcl,12671585,3882608.0,9.163963e+07
27,Duloxetine Hcl,Duloxetine Hcl,12205512,2463985.0,3.986523e+08
28,Fluticasone Propionate,Fluticasone Propionate,12160311,4900604.0,2.014486e+08
29,Montelukast Sodium,Montelukast Sodium,11931030,3062343.0,1.906568e+08

## Step 3: Oncology Drug Search

Search for oral chemotherapy and targeted therapy agents likely to appear in Part D.
IV chemotherapy (5-FU, oxaliplatin) is billed under Medicare Part B, not Part D,
so it will not appear here. Oral agents taken at home are Part D covered.

In [4]:
# Search for oral oncology agents by generic name keywords
onc_keywords = [
    'capecitabine', 'temozolomide', 'imatinib', 'erlotinib', 'gefitinib',
    'lapatinib', 'sunitinib', 'sorafenib', 'everolimus', 'ibrutinib',
    'lenalidomide', 'pomalidomide', 'thalidomide', 'palbociclib',
    'ribociclib', 'abemaciclib', 'olaparib', 'rucaparib', 'niraparib',
    'venetoclax', 'osimertinib', 'alectinib', 'crizotinib'
]

keyword_filter = " OR ".join([f"LOWER(Gnrc_Name) LIKE '%{k}%'" for k in onc_keywords])

onc_drugs = pd.read_sql_query(f"""
    SELECT Gnrc_Name, Brnd_Name, Tot_Prscrbrs, Tot_Clms, Tot_Benes,
           ROUND(Tot_Drug_Cst, 0) AS Tot_Drug_Cst
    FROM part_d_geo
    WHERE Prscrbr_Geo_Lvl = 'National'
      AND ({keyword_filter})
    ORDER BY Tot_Clms DESC
""", conn)

print(f"Oncology drugs found: {len(onc_drugs)}")
onc_drugs

Oncology drugs found: 36

,Gnrc_Name,Brnd_Name,Tot_Prscrbrs,Tot_Clms,Tot_Benes,Tot_Drug_Cst
0,Lenalidomide,Revlimid,11315,216143,36944.0,3.858656e+09
1,Ibrutinib,Imbruvica,9115,151924,17085.0,2.370268e+09
2,Palbociclib,Ibrance,8585,128889,15999.0,2.019562e+09
3,Lenalidomide,Lenalidomide,8741,121722,20385.0,1.680454e+09
4,Imatinib Mesylate,Imatinib Mesylate,9949,115874,14601.0,2.108899e+08
5,Venetoclax,Venclexta,8944,89227,18750.0,8.139482e+08
6,Pomalidomide,Pomalyst,7108,78680,12722.0,1.708116e+09
7,Osimertinib Mesylate,Tagrisso,5422,70781,9373.0,1.230787e+09
8,Abemaciclib,Verzenio,5503,50457,8213.0,7.566754e+08
9,Everolimus,Everolimus,5471,36192,6716.0,2.405536e+08
10,Olaparib,Lynparza,4707,34410,5957.0,4.867162e+08
11,Ribociclib Succinate,Kisqali,3573,24572,4536.0,3.704559e+08
12,Alectinib Hcl,Alecensa,1473,11003,1457.0,1.857217e+08
13,Niraparib Tosylate,Zejula,1596,10016,1884.0,1.614275e+08
14,Sunitinib Malate,Sunitinib Malate,1343,7208,1342.0,6.065528e+07
15,Imatinib Mesylate,Gleevec,1005,6802,863.0,7.319246e+07
16,Erlotinib Hcl,Erlotinib Hcl,991,6145,952.0,1.210512e+07
17,Venetoclax,Venclexta Starting Pack,2329,3425,3394.0,1.122405e+07
18,Sorafenib Tosylate,Sorafenib,881,3409,914.0,3.237936e+07
19,Rucaparib Camsylate,Rubraca,557,3077,554.0,4.300104e+07
20,Thalidomide,Thalomid,502,2707,499.0,1.938501e+07
21,Crizotinib,Xalkori,438,2601,386.0,5.211322e+07
22,Ribociclib Succinate/Letrozole,Kisqali Femara Co-Pack,266,1715,263.0,2.678177e+07
23,Everolimus,Afinitor,376,1577,368.0,2.975510e+07
24,Lapatinib Ditosylate,Lapatinib,302,1536,259.0,7.635448e+06
25,Sorafenib Tosylate,Nexavar,187,686,176.0,8.471542e+06
26,Sunitinib Malate,Sutent,143,632,124.0,7.397129e+06
27,Everolimus,Zortress,119,544,110.0,1.994088e+06
28,Gefitinib,Iressa,89,428,90.0,3.529858e+06
29,Capecitabine,Capecitabine,98,319,86.0,5.036500e+04
30,Lapatinib Ditosylate,Tykerb,76,261,73.0,2.216501e+06
31,Gefitinib,Gefitinib,73,253,74.0,1.098472e+06
32,Everolimus,Afinitor Disperz,28,151,19.0,5.349230e+06
33,Temozolomide,Temozolomide,44,146,41.0,9.255400e+04
34,Niraparib/Abiraterone,Akeega,15,31,16.0,5.665630e+05
35,Capecitabine,Xeloda,9,16,NaN,7.970000e+03

## Step 4: State Coverage Check

For a geographic map to work, a drug needs state-level rows for most or all 50 states.
Check how many states have data for capecitabine specifically.

In [5]:
cape_states = pd.read_sql_query("""
    SELECT Prscrbr_Geo_Desc, Tot_Prscrbrs, Tot_Clms, Tot_Benes,
           ROUND(Tot_Drug_Cst, 0) AS Tot_Drug_Cst
    FROM part_d_geo
    WHERE Prscrbr_Geo_Lvl = 'State'
      AND LOWER(Gnrc_Name) LIKE '%capecitabine%'
    ORDER BY Tot_Clms DESC
""", conn)

print(f"States with capecitabine data: {len(cape_states)}")
cape_states

States with capecitabine data: 13

   Prscrbr_Geo_Desc  Tot_Prscrbrs  Tot_Clms Tot_Benes  Tot_Drug_Cst
0           Georgia             7        33      None        3371.0
1         Wisconsin             6        28      None        1372.0
2         Minnesota             4        25      None        2730.0
3        California            10        24      None        1098.0
4        Washington             4        19      None        1427.0
5       Mississippi             3        17      None        1592.0
6    South Carolina             4        17      None        1059.0
7          Virginia             2        15      None         828.0
8            Kansas             3        14      None        2383.0
9    North Carolina             2        13      None         738.0
10         Maryland             4        11      None         510.0
11        Tennessee             4        11      None        2869.0
12            Texas             4        11      None         489.0

## Step 5: Suppression Rate

CMS suppresses values when fewer than 11 beneficiaries received a drug in a given area.
High suppression in a drug's state rows means the map will have gaps.

In [6]:
# Check suppression rate across all state-level rows
suppression = pd.read_sql_query("""
    SELECT
        COUNT(*) AS total_state_rows,
        SUM(CASE WHEN Tot_Clms IS NULL THEN 1 ELSE 0 END) AS suppressed_rows,
        ROUND(100.0 * SUM(CASE WHEN Tot_Clms IS NULL THEN 1 ELSE 0 END) / COUNT(*), 1) AS pct_suppressed
    FROM part_d_geo
    WHERE Prscrbr_Geo_Lvl = 'State'
""", conn)

print("State-level suppression summary:")
print(suppression)

State-level suppression summary:
   total_state_rows  suppressed_rows  pct_suppressed
0            112329                0             0.0